name: ncview_test
channels:
  - conda-forge
dependencies:
  - appdirs=1.4.3              
	- appnope=0.1.0              
	- asn1crypto=1.3.0              
	- astroid=2.4.1              
	- attrs=19.1.0             
	- Automat=0.8.0              
	- backcall=0.1.0              
	- bcrypt=3.1.7              
	- black=19.10b0            
	- bleach=3.1.4              
	- bokeh=1.0.4              
	- Cartopy=0.17.0             
	- certifi=2020.4.5.1         
	- cffi=1.14.0             
	- cftime=1.1.2              
	- chardet=3.0.4              
	- click=7.1.2              
	- click-plugins=1.1.1              
	- cligj=0.5.0              
	- cloudpickle=0.7.0              
	- colorcet=1.0.1              
	- constantly=15.1.0             
	- cryptography=2.9.2              
	- cycler=0.10.0             
	- Cython=0.29.17            
	- cytoolz=0.10.1             
	- dask=1.1.4              
	- datashader=0.6.9              
	- datashape=0.5.4              
	- decorator=4.4.0              
	- defusedxml=0.6.0              
	- Deprecated=1.2.7              
	- descartes=1.1.0              
	- distributed=1.28.1             
	- entrypoints=0.3                
	- Fiona=1.8.4              
	- Flask=1.0.2              
	- Flask-Cors=3.0.7              
	- GDAL=2.3.3              
	- geopandas=0.4.1              
	- geoviews=1.6.2              
	- gevent=1.4.0              
	- greenlet=0.4.15             
	- HeapDict=1.0.1              
	- holoviews=1.11.3             
	- html5lib=1.0.1              
	- hyperlink=19.0.0             
	- idna=2.9                
	- imageio=2.8.0              
	- importlib-metadata=1.5.0              
	- incremental=17.5.0             
	- ipykernel=5.1.4              
	- ipython=7.1.1              
	- ipython-genutils=0.2.0              
	- ipywidgets=7.5.1              
	- isort=4.3.21             
	- itsdangerous=1.1.0              
	- jedi=0.17.0             
	- Jinja2=2.11.2             
	- jsonschema=3.2.0              
	- jupyter=1.0.0              
	- jupyter-client=6.1.3              
	- jupyter-console=6.1.0              
	- jupyter-core=4.6.3              
	- kiwisolver=1.2.0              
	- lazy-object-proxy=1.4.3              
	- llvmlite=0.32.0             
	- locket=0.2.0              
	- lxml=4.5.0              
	- mapclassify=2.0.1              
	- Markdown=3.1.1              
	- MarkupSafe=1.1.1              
	- matplotlib=3.0.3              
	- mccabe=0.6.1              
	- mistune=0.8.4              
	- mkl-fft=1.0.6              
	- mkl-random=1.0.1              
	- msgpack=1.0.0              
	- multipledispatch=0.6.0              
	- munch=2.5.0              
	- nbconvert=5.4.1              
	- nbformat=5.0.6              
	- netCDF4=1.4.2              
	- networkx=2.4                
	- notebook=6.0.3              
	- numba=0.49.0             
	- numpy=1.18.4             
	- olefile=0.46               
	- OWSLib=0.17.1             
	- packaging=20.3               
	- palettable=3.3.0              
	- pandas=0.25.0             
	- pandocfilters=1.4.2              
	- panel=0.1.2              
	- param=1.8.2              
	- parso=0.7.0              
	- partd=0.3.10             
	- pathspec=0.8.0              
	- pexpect=4.8.0              
	- pickleshare=0.7.5              
	- Pillow=6.2.1              
	- pip=20.0.2             
	- prometheus-client=0.7.1              
	- prompt-toolkit=2.0.10             
	- protobuf=3.11.4             
	- psutil=5.7.0              
	- psycopg2=2.8.4              
	- ptyprocess=0.6.0              
	- pyasn1=0.4.5              
	- pyasn1-modules=0.2.6              
	- pycparser=2.20               
	- pyct=0.4.6              
	- pyepsg=0.4.0              
	- Pygments=2.6.1              
	- PyHamcrest=1.9.0              
	- pykdtree=1.3.1              
	- pylint=2.5.2              
	- pyOpenSSL=19.1.0             
	- pyparsing=2.4.7              
	- pyproj=1.9.6              
	- pyrsistent=0.16.0             
	- pysal=2.1.0              
	- pyshp=2.1.0              
	- PySocks=1.7.1              
	- python-dateutil=2.8.1              
	- pytz=2020.1             
	- pyviz-comms=0.7.2              
	- PyWavelets=1.1.1              
	- PyYAML=5.3.1              
	- pyzmq=17.1.2             
	- qtconsole=4.7.3              
	- QtPy=1.9.0              
	- regex=2020.5.14          
	- requests=2.23.0             
	- Rtree=0.9.4              
	- scikit-image=0.16.2             
	- scikit-learn=0.20.1             
	- scipy=1.1.0              
	- seaborn=0.10.1             
	- selenium=3.141.0            
	- Send2Trash=1.5.0              
	- service-identity=18.1.0             
	- setuptools=46.1.3.post20200330
	- Shapely=1.6.4.post1        
	- simplegeneric=0.8.1              
	- six=1.14.0             
	- sortedcontainers=2.1.0              
	- SQLAlchemy=1.3.16             
	- TBB=0.1                
	- tblib=1.6.0              
	- terminado=0.8.3              
	- testpath=0.3.1              
	- toml=0.10.1             
	- toolz=0.10.0             
	- tornado=6.0.4              
	- tqdm=4.46.0             
	- traitlets=4.3.3              
	- Twisted=20.3.0             
	- typed-ast=1.4.1              
	- urllib3=1.25.8             
	- wcwidth=0.1.9              
	- webencodings=0.5.1              
	- Werkzeug=1.0.1              
	- wheel=0.34.2             
	- widgetsnbextension=3.5.1              
	- wrapt=1.12.1             
	- xarray=0.15.0             
	- zict=2.0.0              
	- zipp=3.1.0              
	- zope.interface=4.7.1  